### ISSUE TITLE
Doesn't work on Python 3.7 (I think)

### ISSUE THREAD

**Issue by VDavid003** [YoRyan/nuxhash#30]
Running `nuxhashd` results in this:
```
[vdavid003@DavidArch ~]$ nuxhashd
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/nuxhash/settings.py", line 108, in load_settings
    with open(config_dir/SETTINGS_FILENAME, 'r') as settings_fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/vdavid003/.config/nuxhash/settings.conf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/nuxhashd", line 11, in <module>
    load_entry_point('nuxhash==1.0.0b2', 'console_scripts', 'nuxhashd')()
  File "/usr/lib/python3.7/site-packages/nuxhash/__init__.py", line 3, in nuxhashd
    main()
  File "/usr/lib/python3.7/site-packages/nuxhash/daemon.py", line 74, in main
    nx_settings = settings.load_settings(config_dir)
  File "/usr/lib/python3.7/site-packages/nuxhash/settings.py", line 111, in load_settings
    if err.errno != os.errno.ENOENT:
AttributeError: module 'os' has no attribute 'errno'
2019-07-16 02:45:56,806 CRITICAL: Crash! Killing all miners.
Killed
```
From the `AttributeError: module 'os' has no attribute 'errno'`, I think the problem is Python 3.7, since... well, google.
